# Generated by Django 4.1.7 on 2023-03-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_language_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
