# Generated by Django 4.1.7 on 2023-03-21 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
