# Generated by Django 4.1.7 on 2023-03-21 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_language_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
